name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  create:
    tags:
      - v*
  schedule:
    - cron: '30 6,18 * * *'
    # - cron: '*/5 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Clone main repository
        uses: actions/checkout@v3
          
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
         java-version: '11'
         distribution: 'temurin'
         cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build debug release
        run: ./gradlew assembleDebug

      - name: Build release version
        run: ./gradlew assembleRelease

#       - name: Check Jitpack publishToMavenLocal
#         run: ./gradlew publishToMavenLocal

      - name: Run tests if commit message contains test
        run: ./gradlew test
        if: contains(github.event.head_commit.message, 'test')
